Arthematic Operations

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])
# condition for adddition/Subraction/multiplcation.... is that the size
# equal of both vectors
arr3 = arr1 + arr2
print(arr3)

[ 7  9 11]


In [ ]:
arr4 = arr1 - arr2
print(arr4)

[-3 -3 -3]


In [ ]:
arr5 = arr1 * arr2
print(arr5)

[10 18 28]


In [ ]:
arr6 = arr1 @ arr2
print(arr6)

56


In [ ]:
# @ is used for matric multiplication
arr1 = np.array(((1,2,3),(4,5,6)))
arr2 = np.array(((7,8),(9,10),(11,12)))
arr3 = arr1 @ arr2
print(arr3)


[[ 58  64]
 [139 154]]


In [ ]:
arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])
arr3 = arr2 // arr1
print(arr3)

[2 2 1]


In [ ]:
arr4 = arr1 ** arr2
print(arr4)

[   32   729 16384]


Numpy Functons

In [ ]:
np.sqrt(arr2)
np.log(arr2)
np.sin(arr2)

array([-0.95892427, -0.2794155 ,  0.6569866 ])

In [ ]:
var = np.sum(arr1)
print(var)
pro = np.prod(arr1)
print(pro)

9
24


Statics Functions

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
var = np.mean(arr)
print(var)
var = np.median(arr)
print(var)
var = np.std(arr)
print(var)
var = np.var(arr)
print(var)

5.5
5.5
2.8722813232690143
8.25


Broadcasting

In [ ]:
# broadcasting is conversion of smaller shape to larger
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
arr3 = arr1 + arr2
print(arr3)

#arr2 is converted to 2D

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1],[2], [3]])
arr3 = arr1 + arr2
print(arr3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


Comparasion

In [ ]:
# it basically performs if functionality but more readable
arr1 = np.array([1,2,3])
arr2 = np.array([5,2,9])
arr3 = arr1 == arr2
print(arr3)
arr3 = np.array((1,2,3))
arr4 = (arr1 > arr2) & arr2 == arr3 # multiple conditions
print(arr4)

#copies only when arr 1 is greater than arr2 else dropped
arr4 = arr2[arr2>=5]
print(arr4)# 2 dropped

arr4[arr4==5]= 10
print(arr4)# replaced 5 with 10

[False  True False]
[False False False]
[5 9]
[10  9]


In [ ]:
arr5 = np.logical_and(arr3,arr4)
print(arr5)
# broadcasting rule is, either size should be equal
# else any one of them should be 1 (row/col)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
arr1 = np.array(['True','False','True'])
arr2 = np.array(['True','False','True'])
arr5 = np.logical_and(arr1,arr2)
print(arr5)
# broadcasting rule is, either size should be equal
# else any one of them should be 1 (row/col)

[ True  True  True]
