In [1]:
import numpy as np


# Numpy Array Creation Methods

Numpy is a python library used for scientific computing. It allows to create n-dimensional arrays. It has ability to quickly broadcast functions.
It provides built-in, linear Algebra, statistical distributions, random number capabilities and much more.

Most commonly used numpy array creation methods are discussed below.

## Transforming Standard Python Data Structures

### List Conversion

In [2]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list) # convert list into an array.
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

### Tuple Conversion

In [3]:
my_tuple = 10, 20, 30, 40
arr_tuple = np.array(my_tuple) # array created from tuple.
print(arr_tuple)
type(arr_tuple)

[10 20 30 40]


numpy.ndarray

## Set Conversion

In [4]:
my_set = {"Harry", "King", "Star","King", "Moon"}
arr_set = np.array(my_set)
print(arr_set)
type(arr_set)
# Note: Array created from set will not allow duplicates.

{'King', 'Star', 'Harry', 'Moon'}


numpy.ndarray

### Dictionary Conversion

Dictionary cannot be converted into single array, for dictionary conversion 2 arrays will be created.

First Array: It will have all the keys.

Second Array: It will have all the values.

Direct conversion of dictionary into an array is not compatible as np.array expects iterable like list.

In [5]:
my_dict = {'A':10, 'B':4, 'C':8, 'D':7}

arr1 = np.array(list(my_dict.keys())) # --> array with keys.
arr2 = np.array(list(my_dict.values())) # --> array with values.

print("Array with Keys:\n", arr1)
print("Array with Values:\n", arr2)

print(f"Type of arr1:{type(arr1)}\nType of arr2:{type(arr2)}")

Array with Keys:
 ['A' 'B' 'C' 'D']
Array with Values:
 [10  4  8  7]
Type of arr1:<class 'numpy.ndarray'>
Type of arr2:<class 'numpy.ndarray'>


## Array Creation with built-in functions

### np.arange

In [6]:
array = np.arange(0, 10) # Works like traditional python's range function, will exclude the end value from the array.
print(array)
type(array)


# Step parameter allows you to make steps of specific intervals.
array2 = np.arange(0, 12, 2)
print("\n Array with step size of 2:\n", array2)

[0 1 2 3 4 5 6 7 8 9]

 Array with step size of 2:
 [ 0  2  4  6  8 10]


## np.zeros 

In [7]:
# Entire array will contain zeros.

arr_zeros = np.zeros(shape=(5, 5)) # --> Shape parameter to define shape of an array.

# Default datatype of array created with np.zeros is float.

print(arr_zeros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## np.ones

In [8]:
# Entire array will have 1.
arr_ones = np.ones(shape=(4, 4)) # It works similar to the np.zeros.

print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## np.linspace

Linspace creates an evenly spaced array.

parameters: start_point, end_point, total number of values between start_point and end_point.

Unlike np.arange it includes the end value into the array.

In [9]:
linspace_arr = np.linspace(start = 1, stop = 10, num = 5)
print(linspace_arr)

[ 1.    3.25  5.5   7.75 10.  ]


### np.eye

It is used to create identity matrix/array i.e. matrix/array having all diagonal enteries 1.

In [10]:
identity_matrix = np.eye(5) # Creates an identity matrix of order 5 by 5.

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array Creation with random numbers.

### np.random.rand

Creates an array of random numbers drawn from a uniform distribution over the range [0,1).

0 is inclusive, 1 is exlusive

Parameters: first argument = no.of row, second argument = no.of columns

In [11]:
rand_arr = np.random.rand(1)
print("Random array between 0 and 1:\n", rand_arr)

rand_arr2 = np.random.rand(3, 3)
print("\nRandom array of shape 3 by 3:\n", rand_arr2)

Random array between 0 and 1:
 [0.92259392]

Random array of shape 3 by 3:
 [[0.95853715 0.71309582 0.72197021]
 [0.79573604 0.35345297 0.86230193]
 [0.22562347 0.6471985  0.58543766]]


### np.random.randn

Creates a random array from standard normal distribution.

Standard normal distribution refers to a normal distribution with mean of 0 and standard deviation of 1.

Values in array will be centered around 0, with most of the values falling within in the range of -3 to 3.



In [12]:
arr = np.random.randn(10)
print(arr)

arr_ = np.random.randn(3, 3)
print("\n", arr_)

[ 0.07556844  1.87489733 -0.36730524 -0.28356289 -2.05635364 -0.49660477
  0.28265597  1.59539293 -0.76764087 -1.80735558]

 [[ 0.58754368  0.2852985   0.75899554]
 [-0.16603266  0.63047706  1.90241673]
 [-0.43943501  0.85138849  0.11854918]]


### np.random.randint

Parameters: lower_threshold, higher_threshold (exclusive), size.

Generates random array of integers.

Shape can also be defined.

In [13]:
arr = np.random.randint(0, 10, size = 3)
print(arr)

arr_ = np.random.randint(0, 100, size = (5, 5)) # Creates an array of 5 X 5
print("\n5 X 5 array:\n", arr_)

[1 6 1]

5 X 5 array:
 [[30 35 51 38 44]
 [71 15 21 15  1]
 [85 25 22 80 22]
 [83 95 64 92 76]
 [19 95 81 74 81]]


### np.random.seed

In [14]:
np.random.seed(101) # intializes random number generation based on a specific value.
myarr = np.random.randint(0, 100, size=10)
myarr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

## Finding Max and Min Values along with their indexes.

In [15]:
myarr = np.arange(1, 10)
print(myarr)
print("Maximum Value:", myarr.max())
print("Index of Maximum Value:", myarr.argmax()) # returns index of max value in an array.

[1 2 3 4 5 6 7 8 9]
Maximum Value: 9
Index of Maximum Value: 8


In [16]:
print("Minimum Value:", myarr.min())
print("Index of Minimum Value:", myarr.argmin())

Minimum Value: 1
Index of Minimum Value: 0


### Shape and reshape

In [17]:
myarr = np.arange(1, 15)
print(myarr)

# Shape is used to check number of rows and columns in an array. It return number of elements in a row for 1-Dimensional array.
print("\n Shape:", myarr.shape)

# Reshape is used to convert the shape of an array into your desired shape.
reshaped_arr = myarr.reshape(2, 7) # --> 2-dimensional array having 2 rows and 7 columns will be created.
print("\nReshaped array:\n", reshaped_arr)
print("\nShape:", reshaped_arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 Shape: (14,)

Reshaped array:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

Shape: (2, 7)


# Indexing and Selection

In [18]:
arr = np.arange(0, 100).reshape(10, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Selection of values at desired index

In [19]:
val_0 = arr[0, 0] # selecting 0th row and 0th column i.e. 0.
print("Selected_value: ", val_0) 

val_33 = arr[3, 3] # selecting element in 3rd row and 3rd column i.e. 33.
print("Selected_value: ", val_33)

val_88 = arr[8, 8] # selecting element in 8th row and 8th column i.e. 88.
print("Selected_value: ", val_88)



Selected_value:  0
Selected_value:  33
Selected_value:  88


### Slicing an array

In [20]:
arr = np.arange(0, 100).reshape(10, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Creating a 3x3 array with slicing.

sliced_3x3_array = arr[4:7, 0:3] # --> It means start from 4th index row upto 7th index row (excluded) and start from column 0 upto 3rd column (excluded).
print("3 X 3 array:\n", sliced_3x3_array)
print("Shape: ", sliced_3x3_array.shape)

3 X 3 array:
 [[40 41 42]
 [50 51 52]
 [60 61 62]]
Shape:  (3, 3)


## Array Broadcasting

Broadcasting allows numpy with arrays of different dimensions perform element-wise operations. The smaller is stretched or broacast across larger array
so that they have compatible shapes. This avoids loops.

During broadcasting physcial shape/dimensions of smaller array are not changed, It only behaves larger array.


In [22]:
big_arr = np.array([[3, 4, 5, 6, 7], [8, 9, 10, 11, 12]]) # 2-dimensional array.
small_arr = np.array([1]) # 1-dimensional array with only single element.

new_arr = big_arr + small_arr
print(new_arr)

# Notice that dimensions of array differ but addition is still performed due to broadcasting.
# small_arr is stretched to match big_arr, making the addition possible.

[[ 4  5  6  7  8]
 [ 9 10 11 12 13]]


## Conditonal Selection in Arrays.
Conditional Selection allows you select elements from an array based on specific condition.

This allows you to filter array based on some condition.

It is performed element-wise i.e. on every single element of an array.

It creates a boolean array equivalent to the size of original array which can then be used for filtering.

In [23]:
arr = np.arange(0, 50).reshape(5, 10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [24]:
arr > 10  

# Checking which elements are greater than 10. It returns true for those elements which are greater than 10.
# Note that shape/dimensions of boolean array is same as that of original array.

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

### Filtering array based on boolean array.

In [25]:
bool_arr = arr % 2 == 0 # condition to create boolean array to filter even numbers.

# Apply boolean array on real array to filter.

even_arr = arr[bool_arr]
print(even_arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


### Prime Number Example

In [26]:
def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_mask = np.vectorize(is_prime)(arr) # np.vectorize is used to apply function to entire array element-wise.
                                         # np.vectorize takes e function as an argument.
prime_num_arr = arr[prime_mask]
print(prime_num_arr)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


# Universal Numpy Functions

## Statistical Functions

In [27]:
arr = np.arange(0, 25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### np.mean

In [28]:
mean = np.mean(arr)
print("Mean:", mean)

Mean: 12.0


### np.sum

In [29]:
Sum = np.sum(arr)
print("Sum:", Sum)

Sum: 300


### np.median

In [30]:
median = np.median(arr)
print("Median:", median)

Median: 12.0


### np.var

In [31]:
variance = np.var(arr) # it calculates variance for an array.
print("Variance:", variance)

Variance: 52.0


### np.std

In [32]:
standard_deviation = np.std(arr)
print("Standard_deviation:", standard_deviation)

Standard_deviation: 7.211102550927978


## Trignometric Functions

### np.sin

In [33]:
sine = np.sin(arr) # computes sine of each element in the array and return an array.
print("Sine array:\n", sine)

Sine array:
 [[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]
 [ 0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836]]


### np.cos

In [34]:
cosine = np.cos(arr) # Computes cos for each element in the array returns an array.
print("Cosine array:\n", cosine)

Cosine array:
 [[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
 [-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722]
 [-0.75968791 -0.95765948 -0.27516334  0.66031671  0.98870462]
 [ 0.40808206 -0.54772926 -0.99996083 -0.53283302  0.42417901]]


### np.tan

In [35]:
tangent = np.tan(arr) # Computes tan for each element in the array returns an array.
print("Tangent array:\n", tangent)

Tangent array:
 [[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
   1.15782128e+00]
 [-3.38051501e+00 -2.91006191e-01  8.71447983e-01 -6.79971146e+00
  -4.52315659e-01]
 [ 6.48360827e-01 -2.25950846e+02 -6.35859929e-01  4.63021133e-01
   7.24460662e+00]
 [-8.55993401e-01  3.00632242e-01  3.49391565e+00 -1.13731371e+00
   1.51589471e-01]
 [ 2.23716094e+00 -1.52749853e+00  8.85165604e-03  1.58815308e+00
  -2.13489670e+00]]


### np.arcsin

In [36]:
inverse_sine = np.arcsin(arr) # Computes sine inverse(sin^-1) for each element and return an array.
print("Inverse Sine Array:\n", inverse_sine)

Inverse Sine Array:
 [[0.         1.57079633        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]]


C:\Users\Waqar\AppData\Local\Temp\ipykernel_11544\2470109983.py:1: RuntimeWarning: invalid value encountered in arcsin
  inverse_sine = np.arcsin(arr) # Computes sine inverse(sin^-1) for each element and return an array.


Note: The above warning occurs when input values are outside valid range of arcsin i.e. [-1, 1]. It applies to all inverse trignometric functions.

### np.arccos

In [37]:
inverse_cosine =  np.arccos(arr) # Computes inverse cos (cos^-1) for each element and return an array.
print("Inverse Cosine array:\n", inverse_cosine)

Inverse Cosine array:
 [[1.57079633 0.                nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]]


C:\Users\Waqar\AppData\Local\Temp\ipykernel_11544\2942899501.py:1: RuntimeWarning: invalid value encountered in arccos
  inverse_cosine =  np.arccos(arr) # Computes inverse cos (cos^-1) for each element and return an array.


### np.arctan

In [38]:
inverse_tangent =  np.arctan(arr) # Computes inverse tan (tan^-1) for each element and return an array.
print("Inverse Tangent array:\n", inverse_tangent)

Inverse Tangent array:
 [[0.         0.78539816 1.10714872 1.24904577 1.32581766]
 [1.37340077 1.40564765 1.42889927 1.44644133 1.46013911]
 [1.47112767 1.48013644 1.48765509 1.49402444 1.49948886]
 [1.50422816 1.50837752 1.5120405  1.51529782 1.51821327]
 [1.52083793 1.52321322 1.52537305 1.52734543 1.52915375]]


## Simple Mathematical Functions

In [39]:
arr_A = np.arange(1, 5)
arr_B = np.arange(6, 10)

print("Array A:\n", arr_A)
print("Array B:\n", arr_B)

Array A:
 [1 2 3 4]
Array B:
 [6 7 8 9]


### np.add

In [40]:
sum_arr = np.add(arr_A, arr_B) # performs addition element-wise and returns an array. 
print("Sum Array:\n", sum_arr)

Sum Array:
 [ 7  9 11 13]


### np.subtract

In [41]:
difference_arr = np.subtract(arr_A, arr_B) # performs subtraction element-wise and returns an array. 
print("Difference Array:\n", difference_arr)

Difference Array:
 [-5 -5 -5 -5]


### np.multiply

In [42]:
product_arr = np.multiply(arr_A, arr_B) # performs multiplication element-wise and returns an array. 
print("Product Array:\n", product_arr)

Product Array:
 [ 6 14 24 36]


### np.divide

In [43]:
quotient_arr = np.divide(arr_A, arr_B) # performs division element-wise and returns an array. 
print("Quotient Array:\n", quotient_arr)

Quotient Array:
 [0.16666667 0.28571429 0.375      0.44444444]


### np.power

In [44]:
result = np.power(arr_A, arr_B) # performs raise arr_A to the power of arr_B element-wise i.e. arr_A^arr_B.
print("Resultant Array:\n", result)

Resultant Array:
 [     1    128   6561 262144]
